### ISSUE TITLE
Command 'boo' not found.

### ISSUE THREAD

**Issue by JsHuang** [jtpereyda/boofuzz#335] opened 2019-10-15 09:12 UTC
While install boofuzz from source, `boo` command can not use. How to solve this?
```
boo open boofuzz-results/run-2019-10-15T08-55-30.db 

Command 'boo' not found, did you mean:

  command 'bos' from deb openafs-client
  command 'goo' from deb goo
  command 'bro' from deb bro
  command 'boom' from deb alliance
  command 'boom' from deb doomsday
  command 'boom' from deb prboom-plus
  command 'woo' from deb python-woo
  command 'boog' from deb alliance
  command 'bobo' from deb python-bobo
  command 'bovo' from deb bovo

Try: apt install <deb name>

```

> System info : Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SR4ven** [comment] 2019-10-18 06:51
I remember having the same issue with Ubuntu Bionic. I can't remember how exactly I fixed it, but I think I moved and renamed the boofuzz/cli.py to /usr/local/bin.
The cause for this seems to be pip trying to install the cli script into /urs/bin, which won't work when installing without root rights.

Currently I'm using Ubuntu Disco (19.04) and I think this problem was solved in combination with the current pip version.
I experienced this issue quite a while ago, so I'm not exactly sure about this anymore. It would be nice, if you could verify my guesses.

**Comment by JsHuang** [comment] 2019-10-24 04:29
This still don't work, it will throw import error:
```
Traceback (most recent call last):
  File "/usr/local/bin/boo", line 9, in <module>
    from . import constants, sessions
ValueError: Attempted relative import in non-package
```

**Comment by SR4ven** [comment] 2019-11-02 00:47
@JsHuang I just reinstalled boofuzz on Ubuntu 19.04 and I wasn't able to reproduce your problem.
Using `pip install -e . --user` installed an entry point script into `/home/<user>/.local/bin` named `boo`.
```python
#!/usr/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys

from boofuzz.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

The `--user` option is important here. For a system wide installation to `/usr/bin` without the user option, root rights are required.

**Comment by jtpereyda** [comment] 2019-11-02 01:36
@JsHuang I would recommend reinstalling as @SR4ven mentioned.

Sometimes you can get weird situations with Python installs, since your system could have mutliple Python installations, you can install to several directories, and sometimes an old or bad installation can stick around.

That sort of install problem can be tricky to debug. But if, after reinstalling as @SR4ven described, you get the same error from `/usr/local/bin/boo`, you could start by deleting/moving that file (`/usr/local/bin/boo`).

**Comment by jtpereyda** [comment] 2019-11-02 01:38
Another workaround you might try is running `python -m boo --help` instead of `boo --help`.

**Comment by JsHuang** [comment] 2019-11-05 04:37
> Well, it is a kinda lame solution, but if you have Boofuzz installed, you can rewrite these imports in `cli.py` on line 9 to `from boofuzz import constants, sessions` and it should work.

Thanks, I reinstall boofuzz still has problem but that works !

**Comment by SR4ven** [comment] 2019-11-08 23:56
Closing as I'm not able to reproduce this issue.

Please comment if you have the same problem and can provide some additional info!

**Closed by SR4ven** 2019-11-08 23:56 UTC
